# Generated by Django 4.2.20 on 2026-02-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rachunki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='year',
            field=models.IntegerField(choices=[(2025, '2025'), (2026, '2026')]),
        ),
    ]
