# Generated by Django 4.2.20 on 2026-02-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbb', '0002_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_process', 'In Process'), ('done', 'Done')], default='not_started', max_length=20),
        ),
    ]
